# Generated by Django 3.1.7 on 2021-04-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0008_auto_20210405_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bb',
            name='_content_rendered',
        ),
        migrations.AlterField(
            model_name='bb',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
