# Generated by Django 3.1.7 on 2021-04-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0009_auto_20210405_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='Image')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
