# Generated by Django 3.1.7 on 2021-04-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0012_auto_20210405_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Image'),
        ),
    ]
